Core_Proje/Controllers/FeatureController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Core_Proje.Controllers
{
    public class FeatureController : Controller
    {
        FeatureManager featureManager = new FeatureManager(new EfFeatureDal());
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.v1 = "Düzenleme";
            ViewBag.v2 = "Öne Çıkanlar";
            ViewBag.v3 = "Öne Çıkanlar";
            var values = featureManager.TGetByID(1);
            return View(values);
        }

        [HttpPost]
        public IActionResult Index(Feature feature)
        {
            featureManager.TUpdate(feature);
            return RedirectToAction("Index","Default");
        }
    }
}

Core_Proje/Views/Feature/Index.cshtml
@model EntityLayer.Concrete.Feature
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@* 1. parametre action ismi
2. parametre controller
3. parametre form methot türü *@
@using (Html.BeginForm("Index", "Feature", FormMethod.Post))
{
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <form class="forms-sample">
                    @Html.HiddenFor(x => x.FeatureID) @* id tutulacak burda *@

                    <div class="form-group">
                        <label>Başlık</label>
                        @Html.TextBoxFor(x => x.Header, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Ad - Soyad</label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Görev</label>
                        @Html.TextBoxFor(x => x.Title, new { @class = "form-control" })
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                    <button class="btn btn-dark">İptal</button>
                </form>
            </div>
        </div>
    </div>
}